### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by zzo38** [Alhadis/Atom-PostScript#1]
See the issue: https://github.com/multiformats/multicodec/issues/278 It is supposed to be a PostScript code but there are some unusual things with the syntax highlighting.

I am guessing that it might be confused by the use of the `currentfile` operator. However, in this case the `currentfile` is inside of a `{}` block, and therefore is not executed right away and does not access the data inside of the `{}` block.

**Comment by Alhadis** [comment]
> I am guessing that it might be confused by the use of the `currentfile` operator.

Yup, spot on. The offending rules in particular are [here](https://github.com/Alhadis/Atom-PostScript/blob/773e8711263ea7fa1ae4c319057c271005eb59d0/grammars/postscript.cson#L368-L446); the comments elucidate my original intent. 🤦 No idea how I forgot about something as obvious as procedure bodies: this is a good reason why additions at the 11th hour are a bad idea. 😁

Also sorry about the slow response. 😢 The fix I've applied will only show up with the next release of Linguist… and there was a [new release](https://github.com/github/linguist/pull/5972) cut this afternoon. 🤦 So it could be a while until you see this fix take effect on GitHub.com (again… my bad 😰).
